"""Availability fault operators over per-step observation dictionaries.

An observation at control step ``t`` is a mapping ``{camera_id: frame}`` where
``frame`` is any object (a NumPy array, a nested list, a test sentinel, ...).
The injector rewrites that mapping according to a :class:`FaultSchedule` and
returns, for every step, the delivered observation, a per-camera availability
mapping and an auditable trace record.

Canonical availability modes (aliases in :data:`MODE_ALIASES`):

``hard_missing``
    Frame is ``None`` and ``available=False``.
``blackout``
    Frame is an all-zero frame of the same shape; ``available=True``.  The
    zero frame is fixed, so every arm sees the same pixels; only the
    availability semantics differ upstream.
``freeze``
    Repeats the last frame captured *strictly before* the onset step;
    ``available=True``.  If ``onset_step == 0`` no pre-onset frame exists and
    the operator degrades to ``hard_missing`` (never to ``blackout``, which
    would silently merge two distinct fault representations).
``stale_k``
    Delivers the frame captured ``k`` steps earlier if it exists, with
    ``available=True`` and ``source_age_steps = k``.  If the history is too
    short the step degrades to ``hard_missing``.  This is the documented
    *available-but-delayed* exception to the causal rule below: a stale camera
    may deliver post-onset frames because the stream is declared available.
``burst_dropout``
    A deterministic binary availability sequence generated by
    :func:`burst_schedule`.  During unavailable blocks the camera behaves as
    ``hard_missing``; during available blocks it is healthy.

Causal rule (enforced by :class:`FaultInjector` and checked by
:func:`poison_test`): for a camera that is *unavailable* at step ``t`` the
injector never delivers a frame whose ``source_step >= onset_step``.  Hidden
post-onset frames of an unavailable camera exist only for the scorer.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from typing import Any, Callable, Iterable, Mapping, Optional

CANONICAL_MODES = ("hard_missing", "blackout", "freeze", "stale_k", "burst_dropout")
MODE_ALIASES = {"missing": "hard_missing", "burst": "burst_dropout", "stale": "stale_k"}
RECOVERY_MODES = ("none", "single_recovery", "periodic_burst")


class CausalViolation(AssertionError):
    """Raised when a hidden post-onset frame would reach an unavailable camera."""


def canonical_mode(name: str) -> str:
    """Resolve a mode name or alias to its canonical name.

    Raises ``ValueError`` for unknown modes.
    """
    key = str(name).strip().lower()
    key = MODE_ALIASES.get(key, key)
    if key not in CANONICAL_MODES:
        raise ValueError(f"unknown availability fault mode: {name!r}")
    return key


# ---------------------------------------------------------------------------
# Deterministic burst schedule
# ---------------------------------------------------------------------------

#: Failure Form is specified in milliseconds so that one canonical setting means
#: the same thing on platforms with different control rates. Ten steps of stale
#: vision is half a second at 20 Hz and a third of one at 30 Hz; 500 ms is 500
#: ms everywhere.
CANONICAL_STALE_MS = 500
CANONICAL_BURST_BLOCK_MS = 500


def control_steps_for(milliseconds: float, control_hz: float) -> int:
    """Convert a canonical duration to this platform's control steps."""
    if control_hz <= 0:
        raise ValueError("control_hz must be > 0")
    if milliseconds < 0:
        raise ValueError("milliseconds must be >= 0")
    return max(1, int(milliseconds * control_hz / 1000.0 + 0.5))


def burst_draw(fault_seed: int, block_index: int, salt: str = "avail") -> float:
    """Deterministic uniform draw in ``[0, 1)`` for one burst block.

    ``SHA256("mcr_bench.burst|<fault_seed>|<block_index>|<salt>")`` is taken and
    the first eight bytes are scaled to ``[0, 1)``: one stable hash draw per
    key tuple, so the same seed and block always give the same draw.
    """
    # The payload prefix is a frozen identifier: changing it would change
    # every burst schedule.
    payload = f"mcr_bench.burst|{int(fault_seed)}|{int(block_index)}|{salt}".encode("utf-8")
    digest = hashlib.sha256(payload).digest()
    return int.from_bytes(digest[:8], "big") / 2**64


def burst_available(fault_seed: int, rel_step: int, burst_frames: int, available_rate: float) -> bool:
    """Availability of relative step ``rel_step`` under the burst rule.

    One draw is made per burst block of ``burst_frames`` steps
    (``block = rel_step // burst_frames``); the block is available iff
    ``draw < available_rate``.

    **The first block is always unavailable**, whatever the draw says. Without
    that, a burst cell whose first block happened to come up available would
    begin with no fault at all, and its onset would be somewhere later than the
    one the manifest records -- so two scenes with the same nominal onset would
    have been faulted at different points, and the difference would look like
    policy behaviour.
    """
    if burst_frames < 1:
        raise ValueError("burst_frames must be >= 1")
    if not 0.0 <= available_rate <= 1.0:
        raise ValueError("available_rate must be in [0, 1]")
    block = rel_step // burst_frames
    if block == 0:
        return False
    return burst_draw(fault_seed, block) < available_rate


def burst_schedule(fault_seed: int, n_steps: int, burst_frames: int, available_rate: float) -> list[bool]:
    """Binary availability sequence for ``n_steps`` relative steps.

    The sequence is a pure function of its arguments; the same fault seed
    always yields the same bits, so the schedule can be stored in a manifest
    and hashed (see :func:`burst_hash`).
    """
    return [burst_available(fault_seed, s, burst_frames, available_rate) for s in range(int(n_steps))]


def burst_hash(bits: Iterable[bool]) -> str:
    """SHA256 hex digest of a binary availability sequence."""
    return hashlib.sha256("".join("1" if b else "0" for b in bits).encode("ascii")).hexdigest()


# ---------------------------------------------------------------------------
# Zero frames
# ---------------------------------------------------------------------------

def zero_like(frame: Any) -> Any:
    """Return an all-zero frame with the same shape/type as ``frame``.

    Supports NumPy arrays (``zeros_like``), numbers, bytes and nested
    lists/tuples.  Other objects fall back to ``0`` so that the operator still
    delivers *something* that is unmistakably not the healthy frame.
    """
    try:
        import numpy as np
    except ImportError:  # pragma: no cover
        np = None
    if np is not None and isinstance(frame, np.ndarray):
        return np.zeros_like(frame)
    if isinstance(frame, bool):
        return False
    if isinstance(frame, (int, float)):
        return type(frame)(0)
    if isinstance(frame, (bytes, bytearray)):
        return type(frame)(len(frame))
    if isinstance(frame, (list, tuple)):
        return type(frame)(zero_like(v) for v in frame)
    return 0


# ---------------------------------------------------------------------------
# Schedule
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class FaultSchedule:
    """Frozen description of one availability fault cell.

    Parameters
    ----------
    faulted_cameras:
        Camera ids affected by the fault.
    mode:
        Canonical mode or alias (resolved on construction).
    onset_step:
        First faulted control step (inclusive).
    end_step:
        First step after the fault (exclusive); ``None`` = until episode end.
    stale_k:
        Delay in control steps for ``stale_k``.
    burst_frames, available_rate:
        Burst-block length and per-block availability probability for
        ``burst_dropout``.
    recovery:
        ``none`` (permanent), ``single_recovery`` (healthy again from
        ``end_step``) or ``periodic_burst`` (only meaningful with
        ``burst_dropout``).
    """

    faulted_cameras: frozenset[str]
    mode: str = "hard_missing"
    onset_step: int = 0
    end_step: Optional[int] = None
    stale_k: Optional[int] = None
    burst_frames: int = 15
    available_rate: float = 0.5
    fault_seed: int = 0
    recovery: str = "none"

    def __post_init__(self) -> None:
        object.__setattr__(self, "faulted_cameras", frozenset(str(c) for c in self.faulted_cameras))
        object.__setattr__(self, "mode", canonical_mode(self.mode))
        if self.onset_step < 0:
            raise ValueError("onset_step must be >= 0")
        if self.end_step is not None and self.end_step <= self.onset_step:
            raise ValueError("end_step must be > onset_step (exclusive end) or None")
        if self.recovery not in RECOVERY_MODES:
            raise ValueError(f"unknown recovery mode {self.recovery!r}; expected one of {RECOVERY_MODES}")
        if self.recovery == "none" and self.end_step is not None:
            raise ValueError("recovery='none' means permanent failure; end_step must be None")
        if self.recovery == "single_recovery" and self.end_step is None:
            raise ValueError("recovery='single_recovery' requires a finite end_step")
        if self.recovery == "periodic_burst" and self.mode != "burst_dropout":
            raise ValueError("recovery='periodic_burst' requires mode='burst_dropout'")
        if self.mode == "stale_k" and (self.stale_k is None or self.stale_k < 1):
            raise ValueError("stale_k mode requires stale_k >= 1")
        if self.mode == "burst_dropout":
            if self.burst_frames < 1:
                raise ValueError("burst_frames must be >= 1")
            if not 0.0 <= self.available_rate <= 1.0:
                raise ValueError("available_rate must be in [0, 1]")

    def active(self, step: int) -> bool:
        """Whether the fault window covers ``step``."""
        if step < self.onset_step:
            return False
        return self.end_step is None or step < self.end_step


# ---------------------------------------------------------------------------
# Injector
# ---------------------------------------------------------------------------

@dataclass
class TraceRecord:
    """Per-step audit record produced by :meth:`FaultInjector.apply`."""

    step: int
    availability: dict[str, bool]
    source_step: dict[str, Optional[int]]
    source_age_steps: dict[str, Optional[int]]
    faulted_observation_produced: bool
    mode: str
    active: bool

    def as_dict(self) -> dict[str, Any]:
        return {
            "step": self.step,
            "availability": dict(self.availability),
            "source_step": dict(self.source_step),
            "source_age_steps": dict(self.source_age_steps),
            "faulted_observation_produced": self.faulted_observation_produced,
            "mode": self.mode,
            "active": self.active,
        }


class FaultInjector:
    """Stateful availability fault injector.

    Call :meth:`apply` once per control step, in increasing step order, with
    the *healthy* observation for that step.  The injector keeps the healthy
    history it needs (freeze / stale) and enforces the causal rule from the
    module docstring on every delivery.
    """

    def __init__(self, schedule: FaultSchedule) -> None:
        self.schedule = schedule
        self._history: dict[str, dict[int, Any]] = {}
        self._last_step: Optional[int] = None
        self.faulted_observations_produced = 0
        self.trace: list[TraceRecord] = []

    # -- helpers ---------------------------------------------------------
    def _record(self, step: int, healthy_obs: Mapping[str, Any]) -> None:
        for cam, frame in healthy_obs.items():
            self._history.setdefault(cam, {})[step] = frame

    def _pre_onset_frame(self, cam: str) -> tuple[Optional[int], Any]:
        """Latest recorded frame with ``source_step < onset_step``."""
        hist = self._history.get(cam, {})
        # The last frame that was actually there: a pre-onset step whose frame
        # was None is not a frame to freeze on.
        candidates = [s for s in hist if s < self.schedule.onset_step and hist[s] is not None]
        if not candidates:
            return None, None
        s = max(candidates)
        return s, hist[s]

    def _camera_available_this_step(self, step: int) -> bool:
        """Availability for the faulted cameras at ``step`` under ``burst_dropout``."""
        sched = self.schedule
        return burst_available(sched.fault_seed, step - sched.onset_step, sched.burst_frames, sched.available_rate)

    # -- main entry point --------------------------------------------------
    def apply(self, step: int, healthy_obs: Mapping[str, Any]) -> tuple[dict[str, Any], dict[str, bool], TraceRecord]:
        """Apply the fault to ``healthy_obs`` at ``step``.

        Returns ``(obs, availability, trace_record)`` where ``obs`` is the
        observation to hand to the policy, ``availability`` maps every camera
        id to a boolean and ``trace_record`` is a :class:`TraceRecord`.
        """
        if self._last_step is not None and step <= self._last_step:
            raise ValueError(f"steps must be strictly increasing (got {step} after {self._last_step})")
        self._last_step = step
        self._record(step, healthy_obs)
        sched = self.schedule

        obs: dict[str, Any] = {}
        availability: dict[str, bool] = {}
        source_step: dict[str, Optional[int]] = {}
        source_age: dict[str, Optional[int]] = {}
        produced = False
        active = sched.active(step)

        for cam, frame in healthy_obs.items():
            if cam not in sched.faulted_cameras or not active:
                obs[cam] = frame
                availability[cam] = frame is not None
                source_step[cam] = step if frame is not None else None
                source_age[cam] = 0 if frame is not None else None
                continue

            mode = sched.mode
            delivered: Any = None
            avail = False
            src: Optional[int] = None

            if mode == "hard_missing":
                pass
            elif mode == "blackout":
                delivered, avail, src = zero_like(frame), True, step
            elif mode == "freeze":
                src, delivered = self._pre_onset_frame(cam)
                avail = src is not None
                if not avail:
                    delivered, src = None, None  # onset == 0 -> hard_missing
            elif mode == "stale_k":
                k = int(sched.stale_k)
                hist = self._history.get(cam, {})
                if step - k in hist and hist[step - k] is not None:
                    delivered, avail, src = hist[step - k], True, step - k
            elif mode == "burst_dropout":
                if self._camera_available_this_step(step):
                    delivered, avail, src = frame, True, step
            else:  # pragma: no cover - guarded by canonical_mode
                raise ValueError(mode)

            # Causal firewall: an unavailable camera never exposes post-onset frames.
            if not avail and src is not None and src >= sched.onset_step:
                raise CausalViolation(f"camera {cam} unavailable at step {step} but source_step={src}")
            # Freeze must never exceed onset even though it is 'available'.
            if mode == "freeze" and src is not None and src >= sched.onset_step:
                raise CausalViolation(f"freeze delivered post-onset frame {src} at step {step}")

            obs[cam] = delivered
            availability[cam] = avail
            source_step[cam] = src
            source_age[cam] = (step - src) if src is not None else None
            # The injector produces a faulted observation whenever the
            # delivered frame differs from the healthy one at this step. The
            # runner separately records whether a policy query consumed it.
            if not (avail and src == step and delivered is frame):
                produced = True

        if produced:
            self.faulted_observations_produced += 1
        record = TraceRecord(
            step=step,
            availability=availability,
            source_step=source_step,
            source_age_steps=source_age,
            faulted_observation_produced=produced,
            mode=sched.mode,
            active=active,
        )
        self.trace.append(record)
        return obs, availability, record

    def availability_trace_hash(self) -> str:
        """SHA256 over the per-step availability mapping (sorted camera ids)."""
        lines = []
        for rec in self.trace:
            bits = "".join("1" if rec.availability[c] else "0" for c in sorted(rec.availability))
            lines.append(f"{rec.step}:{bits}")
        return hashlib.sha256("\n".join(lines).encode("ascii")).hexdigest()


# ---------------------------------------------------------------------------
# Poison test
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class Poison:
    """Sentinel frame that must never be delivered while a camera is unavailable."""

    camera: str
    step: int


@dataclass(frozen=True)
class HealthyFrame:
    """Sentinel healthy frame (pre-onset or non-faulted camera)."""

    camera: str
    step: int


def poison_test(
    injector: FaultInjector,
    camera_ids: Iterable[str],
    n_steps: int,
    frame_factory: Optional[Callable[[str, int], Any]] = None,
) -> dict[str, Any]:
    """Feed sentinel frames through ``injector`` and assert the causal rule.

    Post-onset frames of the faulted cameras are :class:`Poison` sentinels.
    After every step the helper asserts that

    * every unavailable camera receives ``None`` with no source step;
    * no :class:`Poison` is delivered to a camera whose availability is
      ``False``;
    * in ``freeze`` mode delivered frames always come from before onset.

    ``frame_factory(camera, step)`` may override how healthy (pre-onset)
    frames are built.  Returns a summary dictionary; raises
    :class:`CausalViolation` on the first breach.
    """
    cams = [str(c) for c in camera_ids]
    sched = injector.schedule
    delivered_poison = 0
    unavailable_steps = 0
    for step in range(int(n_steps)):
        healthy: dict[str, Any] = {}
        for cam in cams:
            if cam in sched.faulted_cameras and step >= sched.onset_step:
                healthy[cam] = Poison(cam, step)
            elif frame_factory is not None:
                healthy[cam] = frame_factory(cam, step)
            else:
                healthy[cam] = HealthyFrame(cam, step)
        obs, availability, rec = injector.apply(step, healthy)
        for cam in cams:
            frame = obs[cam]
            if not availability[cam]:
                unavailable_steps += 1
                if frame is not None or rec.source_step[cam] is not None:
                    raise CausalViolation(f"unavailable camera {cam} at step {step} delivered {frame!r}")
            if isinstance(frame, Poison):
                if not availability[cam]:
                    raise CausalViolation(f"poison {frame} delivered while unavailable")
                if sched.mode not in ("stale_k", "burst_dropout", "blackout") and cam in sched.faulted_cameras:
                    raise CausalViolation(f"poison {frame} delivered under mode {sched.mode}")
                delivered_poison += 1
            if sched.mode == "freeze" and cam in sched.faulted_cameras and sched.active(step):
                src = rec.source_step[cam]
                if src is not None and src >= sched.onset_step:
                    raise CausalViolation(f"freeze used post-onset frame {src}")
    return {
        "n_steps": int(n_steps),
        "unavailable_camera_steps": unavailable_steps,
        "poison_delivered_while_available": delivered_poison,
        "faulted_observations_produced": injector.faulted_observations_produced,
        "availability_trace_hash": injector.availability_trace_hash(),
    }
